### ISSUE TITLE
Exit not working with picodom

### ISSUE THREAD

**Issue by zaaack** [zaceno/hyperapp-transitions#6]
https://github.com/picodom/picodom/blob/d2368aacf771032eb7b5e25ff11d9b4e8cbe349e/src/patch.js#L89-L98

picodom is using `onremove` while hyperapp is using `onbeforeremove`, transitions's exit only support `onbeforeremove`.

**Comment by zaceno** [comment]
@zaaack Thanks for reporting. I'm going to fix this soon.

I recently changed exit transitions to be compatible with hyperapp 0.18's onremove behavior. I thought it would not be incompatible with picodom, but I didn't test it... clearly 😛 

Hyperapp 1.0 (coming very soon) will go back to the same onremove behavior picodom has, so it'll be ok for now. But in the long run, if picodom and hyperapp end up diverging permanently, I'll probably have to split this lib into one transition for each.

**Comment by zaceno** [comment]
@zaaack Hyperapp's onremove behavior went back to being similar to Picodom for 1.0, and I updated this lib for that, so it should work now. Can you give it a try again and see if it's ok? Unfortunately I don't have any examples using picodom ready to go (I should though...), but perhaps you do?

**Comment by zaaack** [comment]
@zaceno I tried, `exit` still not working, seems `onremove` in picodom doesn't have second parameter as `ondone` callback to remove the element.
 https://github.com/picodom/picodom/blob/master/src/patch.js#L93

**Comment by zaceno** [comment]
@zaack ok, you're right it's still not quite the same. Ok I'll look into it further. Stay tuned :)

**Comment by zaceno** [comment]
@zaack Ok *now* I think I fixed it (for realz this time ;) ). I added picodom-versions of the examples to the README for verifying compatibility.  Would you confirm it works now, with v0.10.1 of `hyperapp-transitions`?

It ended up not being as nice as I would have liked, since picodom 1.0.2 still uses the hard-to-compose way of deferring element removal with function returns from the lifecycle event. But I  imagine that changing soon, once the discussion about `ondestroy` settles (I imagine it will work the same as in hyperapp today). Once that's settled, I can simplify hyperapp-transitions a bit.

**Comment by zaceno** [comment]
I'm going to close here now, since I was able to verify that the problem was fixed myself. If you're still having issues for some reason, feel free to reopen or open another issue. Thanks again @zaaack!
